// Auto-generated
let project = new Project('main_1_0_0');

project.addSources('Sources');
project.addLibrary("/home/phillip/dev/ArmorySDK/armory");
project.addLibrary("/home/phillip/dev/ArmorySDK/iron");
project.addLibrary("/home/phillip/dev/ArmorySDK/lib/haxebullet");
project.addAssets("/home/phillip/dev/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("/home/phillip/dev/ArmorySDK/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('arm.CameraController');
project.addParameter("--macro keep('arm.CameraController')");
project.addParameter('armory.trait.internal.UniformsManager');
project.addParameter("--macro keep('armory.trait.internal.UniformsManager')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.MainMenuController');
project.addParameter("--macro keep('arm.MainMenuController')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addShaders("build_main/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_main/compiled/Assets/**", { notinlist: true });
project.addAssets("build_main/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("/home/phillip/dev/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/home/phillip/dev/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/home/phillip/dev/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("Bundled/canvas/MainMenu.files", { notinlist: true });
project.addAssets("Bundled/canvas/MainMenu.json", { notinlist: true });
project.addAssets("Bundled/canvas/_themes.json", { notinlist: true });
project.addAssets("textures/grid_base.png", { notinlist: true });
project.addAssets("textures/grid_rough.png", { notinlist: true });
project.addLibrary("/home/phillip/dev/ArmorySDK/lib/zui");
project.addAssets("/home/phillip/dev/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_soundcompress');
project.addDefine('arm_audio');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');


resolve(project);
